eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
spring:
  boot: 
    admin: 
      url: http://localhost:9198 
  boot:
    admin:  
       client: 
           url: http://localhost:9198/
    
